version: '3.8'
services:
 par-fe:
    container_name: parfet-fe-consumer-staging
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3001:3001'
    env_file:
      - .env
      - .env.production
