name: [Production] Parfet-Frontend-Consumer Deployment

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Set env
        run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV

      - name: Create .env file
        run : |
          touch .env
          echo $ENV_CONSUMER_API >> .env
          echo $ENV_PROD_CONSUMER_API >> .env
          echo $ENV_PROD_FIREBASE_API_KEY >> .env
          echo $ENV_PROD_FIREBASE_APP_ID >> .env
          echo $ENV_PROD_FIREBASE_AUTH_DOMAIN >> .env
          echo $ENV_PROD_FIREBASE_MESSAGING_SENDER_ID >> .env
          echo $ENV_PROD_FIREBASE_PROJECT_ID >> .env
          echo $ENV_PROD_FIREBASE_STORAGE_BUCKET >> .env
        shell : bash
        env :
          ENV_CONSUMER_API : ${{secrets.ENV_CONSUMER_API}}
          ENV_PROD_CONSUMER_API : ${{secrets.ENV_PROD_CONSUMER_API}}
          ENV_PROD_FIREBASE_API_KEY : ${{secrets.ENV_PROD_FIREBASE_API_KEY}}
          ENV_PROD_FIREBASE_APP_ID : ${{secrets.ENV_PROD_FIREBASE_APP_ID}}
          ENV_PROD_FIREBASE_AUTH_DOMAIN : ${{secrets.ENV_PROD_FIREBASE_AUTH_DOMAIN}}
          ENV_PROD_FIREBASE_MESSAGING_SENDER_ID : ${{secrets.ENV_PROD_FIREBASE_MESSAGING_SENDER_ID}}
          ENV_PROD_FIREBASE_PROJECT_ID : ${{secrets.ENV_PROD_FIREBASE_PROJECT_ID}}
          ENV_PROD_FIREBASE_STORAGE_BUCKET : ${{secrets.ENV_PROD_FIREBASE_STORAGE_BUCKET}}

      - name: Create .ssh file
        run : |
          touch aws.pem
          echo "${{secrets.SSH_PEM_KEY}}" >> aws.pem
          sudo chmod 400 aws.pem
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
          ssh-keyscan ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
          ls -la


      - name: Cloning repository
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PEM_KEY}}
          script: |
           rm -rf PAR-Frontend-Consumer || :
           git clone git@github.com:Parfet/PAR-Frontend-Consumer.git

      - name: COPY .env 
        run : |
          ls -la
          scp -i "aws.pem" .env ${{ secrets.SSH_USERNAME }}@${{secrets.SSH_HOST}}:~/PAR-Frontend-Consumer/

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{secrets.SSH_PEM_KEY}}
          script: |
           cd PAR-Frontend-Consumer
           git checkout PRODelop
           docker-compose down --rmi local || :
           docker-compose up -d --build
           docker ps -a