name: Deploy Parfet-Frontend-Consumer Application

on:
  push:
    branches: [ main ]

jobs:
  Preparing_ENV:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo ${{ secrets.ENV }} >> .env
          touch .env.production
          echo ${{ secrets.ENV_PRODUCTION }} >> .env.production
  Deployment :  
    runs-on: ubuntu-latest
    steps:  
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{secrets.SSH_PEM_KEY}}
          script: |
           rm -rf PAR-Frontend-Consumer || :
           git clone https://nattaphonmek:Mek.11530@github.com/Parfet/PAR-Frontend-Consumer.git
           scp -i ${{ secrets.SSH_PEM_KEY }} .env* ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }}:~/PAR-Frontend-Consumer/
           cd PAR-Frontend-Consumer
           docker-compose down --rmi local || :
           docker-compose up -d --build
           docker ps -a
